# pipelines.yaml
# Defines all named pipelines for the orchestration framework
# Example structure:
pipelines:
  current_1h:
    priority: 2
    command: "interval:1h,function:fetch,scale:latest"
    schedule: "0 */1 * * *"
    hooks: ["gather", "fetcher", "gap", "aggregate_allmarkets", "indicators"]

  current_6h:
    priority: 2
    command: "interval:6h,function:fetch,scale:latest"
    schedule: "0 */6 * * *"
    hooks: ["gather", "fetcher", "gap", "aggregate_allmarkets", "indicators"]

  current_1d:
    priority: 2
    command: "interval:1d,function:fetch,scale:latest"
    schedule: "0 0 */1 * *"
    hooks: ["gather", "fetcher", "gap", "aggregate_allmarkets", "indicators"]

  historical:
    priority: 8
    hooks: ["gather", "fetcher", "gap", "aggregate_higher_candles", "aggregate_allmarkets", "indicators"]

  fetch_historical:
    priority: 8
    hooks: ["gather", "fetcher", "gap", "aggregate_higher_candles", "aggregate_allmarkets"]

  calculate_all:
    priority: 8
    hooks: ["gather", "indicators"]

  allmarkets:
    priority: 8
    hooks: ["gather", "aggregate_allmarkets"]

  debug:
    priority: 10
    command: "interval:1h"
    hooks: ["gather", "debug"]

